blank_issues_enabled: false
contact_links:
  - name: ESMF Support
    url: mailto:esmf_support@ucar.edu
    about: For help with the use of ESMF or to report a problem, please email esmf_support@ucar.edu.
